spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.173.213:3306/user_center
    username: localroot
    password: 123Lujingrui.
  # session 失效时就按
  session:
    timeout: 86400